# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: ishaker/aws-cli
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: deploy
          command: |
            IMAGE=$aws_account_id/$CIRCLE_PROJECT_REPONAME
            aws configure set aws_access_key_id $accesskey
            aws configure set aws_secret_access_key $secretkey
            eval $(aws ecr get-login --no-include-email --region $region | sed 's;https://;;g')
            docker build -t $IMAGE .
            aws ecr describe-repositories --repository-names $CIRCLE_PROJECT_REPONAME || aws ecr create-repository --repository-name $CIRCLE_PROJECT_REPONAME
            docker push $IMAGE 
  deploy:
    docker: 
      - image: 'ishaker/aws-ecscli'
    steps:
      - checkout
      - run:
          name: Deploy ecs
          command: |
            ./deploy.sh
workflows:
  version: 2.1
  api-deploy:
    jobs:
      - deploy:
          requires:
            - build
      - build
